### PR TITLE
Batch CSVParse results

### LINKED ISSUE #6: Incomplete array jsons
This will be a bit harder to debug, since it seems to happen randomly, but I managed to replicate it (consistently) on CI and (sometimes) locally.

Basically, the JSON files generated by fetch script are incomplete. When doing `tail -n 5 node_modules/openflights-cached/dist/array.json` after installation, I get this:
```
{"airportid":"274","name":"Minna Airport","city":"Minna","country":"Nigeria","iata":"MXJ","icao":"DNMN","latitude":"9.652170181274414","longitude":"6.462259769439697","altitude":"834","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"275","name":"Port Harcourt International Airport","city":"Port Hartcourt","country":"Nigeria","iata":"PHC","icao":"DNPO","latitude":"5.0154900550842285","longitude":"6.94959020614624","altitude":"87","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"276","name":"Sadiq Abubakar III International Airport","city":"Sokoto","country":"Nigeria","iata":"SKO","icao":"DNSO","latitude":"12.916299819946289","longitude":"5.207190036773682","altitude":"1010","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"277","name":"Yola Airport","city":"Yola","country":"Nigeria","iata":"YOL","icao":"DNYO","latitude":"9.257550239562988","longitude":"12.430399894714355","altitude":"599","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"278","name":"Zaria Airport","city":"Zaria","country":"Nigeria","iata":"ZAR","icao":"DNZA","latitude":"11.1302","longitude":"7.68581","altitude":"2170","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"}
```

The JSON array ending and rest of the airports are completely missing. Running it again returns the same results from `tail`. 

It might be just a transient error, but I wanted to put it here in case someone else has it.

### PR DESCRIPTION
**Pull request by wyozi**
Fixes #6

I'm not sure why this works, but seems to do the job.

### CODE REVIEW

**Comment by MichalCz** [comment]
Hey, can you change the target branch to develop?

**Comment by MichalCz** [comment]
I'll check and release.

**Comment by MichalCz** [comment]
Yeah, that sadly didn't help. :(

**Comment by wyozi** [comment]
I'll see if Github actions fare any better. For the record though, the patch I'm using differs a slight bit from this PR:

```patch
diff --git a/bin/fetch.js b/bin/fetch.js
index 436a76f..62ca197 100755
--- a/bin/fetch.js
+++ b/bin/fetch.js
@@ -20,13 +20,14 @@ const awaitWritten = (stream, path) => {
     );
 };
 
+let EXITCONDITION = false;
 (async () => {
     const fetch = () => new Promise(s => get(OPENFLIGHTS_URL, stream => s(stream)).end());
 
     const columns = [
         "airportid", "name", "city", "country", "iata", "icao", "latitude", "longitude", "altitude", "timezone", "dst", "tz", "type", "source"
     ];
-    
+
     let i = 0; let j = 0;
     const stream = StringStream.from(async function() {
         let retries = 5;
@@ -44,15 +45,21 @@ const awaitWritten = (stream, path) => {
         throw new Error("Too many errors...");
     }, {})
         .CSVParse()
-        .each(() => j++)
-        .map(x => x.map(col => col === "\\N" ? "" : col))
-        .map(x => {
-            const out = {};
-            for (let i = 0; i < columns.length; i++) out[columns[i]] = x[i];
+        .batch(100)
+        .map(arr => {
+            return arr.map(x => {
+                const out = {};
+                for (let i = 0; i < columns.length; i++) {
+                    const col = x[i];
+                    out[columns[i]] = col === "\\N" ? "" : col;
+                }
+
+                j++;
 
-            return out;
+                return out;
+            });
         })
-        .each(() => i++)
+        .flatten()
     ;
 
     const dirs = {};
@@ -79,6 +86,18 @@ const awaitWritten = (stream, path) => {
     ]);
 })()
     .then(
-        () => new Promise(res => setTimeout(res, 1000)),
-        (e) => { throw e; }
+        () => {
+            EXITCONDITION = true;
+            console.log("done");
+        },
+        (e) => {
+            EXITCONDITION = true;
+            throw e;
+        }
     );
+const start = +new Date();
+function wait() {
+    if (!EXITCONDITION && (+new Date() - start) < 60000)
+        setTimeout(wait, 1000);
+}
+wait();
```

**Comment by wyozi** [comment]
I think the exit condition might be required. Using 1.2.11 instead of my patched version caused `tail` to print this as the last line:
```
{"airportid":"13610","name":"Karamea Airport","city":"Karamea","country":"New Zealand","iata":"","icao":"NZKM","latitude":"-41.236698150634766","longitude":"172.10499572753906","altitude":"30","timezone":"12","dst":"Z","tz":"","type":"airport","source":"OurAirports"}
```

**Comment by wyozi** [comment]
Okay, I'm confused. Now fetching doesn't work with an exit condition either

**Comment by wyozi** [comment]
Pinning the version to 1.2.9 and applying the patch above seems to be the only way to consistently get the CI to succeed. These errors are too transient :/

**Pull request merged**
